global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/T01xxxxxxGD/B018ZXXXXXXXXF/Pwxe0xxxxxxxxxxxhiq'
  pagerduty_url: 'https://events.pagerduty.com/v2/enqueue'
route:
  receiver: 'smtp-local'
  routes:
    - match:
        severity: critical,warning
      receiver: 'slack-notifications'
      continue: true
    - match:
        severity: critical,warning
      receiver: 'web.hook'
      continue: true
    - match:
        severity: critical,warning
      receiver: 'pagerduty-notifications'
      continue: true
    - match:
        severity: critical,warning
      receiver: 'smtp-local'
      continue: true      
receivers:
  - name: 'smtp-local'
    email_configs:
    - to: 'xxx@xxx.com'
      from: 'xxx@xxx.com'
      smarthost: localhost:25
      require_tls: false
      send_resolved: true
  - name: 'slack-notifications'
    slack_configs:
    - channel: '#monitoring'
      send_resolved: true
      icon_url: https://avatars3.githubusercontent.com/u/3380462
      title: |-
        [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
        {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
          {{" "}}(
          {{- with .CommonLabels.Remove .GroupLabels.Names }}
            {{- range $index, $label := .SortedPairs -}}
              {{ if $index }}, {{ end }}
              {{- $label.Name }}="{{ $label.Value -}}"
            {{- end }}
          {{- end -}}
          )
        {{- end }}
      text: >-
        {{ range .Alerts -}}
        *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
      
        *Description:* {{ .Annotations.description }}
      
        *Details:*
          {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
          {{ end }}
        {{ end }}
  - name: 'web.hook'
    webhook_configs:
    - url: 'http://xxxxxxx:xxxx/xxxx?msisdn=xxxx&text=xxxxx.'
  - name: 'pagerduty-notifications'
    pagerduty_configs:
    - service_key: 3a560cxxxxxxxxxxxxxxxx7c198
      send_resolved: true
  